version: '3'

networks:
  strategio-network:

services:
  app:
    build: .
    restart: "no"
    networks:
      - strategio-network
    ports:
      - "8090:80"
    depends_on:
      - postgres
    volumes:
      - ./docker/nginx:/etc/nginx
      - ./docker/php/8.1/cli/php.ini:/etc/php/8.1/cli/php.ini
      - ./docker/php/8.1/fpm/php.ini:/etc/php/8.1/fpm/php.ini
      - ./docker/php/8.1/fpm/php.ini:/etc/php/8.1/fpm/php-fpm.conf
      - ./docker/php/8.1/fpm/pool.d/www.conf:/etc/php/8.1/fpm/pool.d/www.conf
      - $PWD:/usr/share/nginx/html:cached

  postgres:
    image: postgres:14
    #restart: on-failure because postgres shutdown on first creation (permissions problem)
    restart: "on-failure"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    networks:
      - strategio-network
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./docker/temp/postgres:/var/lib/postgresql/data:cached

  adminer:
    image: dockette/adminer:dg
    restart: "no"
    ports:
      - "9100:80"
    networks:
      - strategio-network